
name: POS-Backend

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration
  data:
    mongodb:
      database: efapsPOS

org:
  quartz:
    threadPool:
      threadCount: 2
    jobs:
      syncReceipts:
        interval: 30  #Interval in seconds

server:
  servlet:
    contextPath: /pos/api


efaps:
  restUrl: http://localhost:8888/eFaps/servlet/rest
  productPath: /pos/products
  categoryPath: /pos/categories
  workspacePath: /pos/workspaces
  posPath: /pos/poss
  userPath: /pos/users
  receiptPath:  /pos/receipts

auth:
  user: Administrator
  password: Administrator

jwt:
  secret: ThisIsNotVerySecret
  expiration: 1000


---

spring:
  profiles: demo
  autoconfigure:
    exclude:
  data:
    mongodb:
      database: efapsDemoPOS

name: POS-Demo-Backend
