
name: POS-Backend

spring:
  data:
    mongodb:
      database: efapsPOS

server:
  servlet:
    contextPath: /pos/api


efaps:
  restUrl: http://localhost:8888/eFaps/servlet/rest
  productPath: /pos/products

auth:
  user: Administrator
  password: Administrator

jwt:
  secret: ThisIsNotVerySecret
  expiration: 1000

