name: POS-Backend

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration
  data:
    mongodb:
      database: efapsPOS

server:
#  address: 192.168.1.100
#  port: 8888
  http2:
    enabled: true

org:
  quartz:
    threadPool:
      threadCount: 2
    jobs:
      syncReceipts:
        interval: 120  #Interval in seconds
      syncInvoices:
        interval: 120  #Interval in seconds
      syncTickets:
        interval: 120  #Interval in seconds

efaps:
  baseUrl: http://localhost:8888/eFaps
  productPath: /servlet/rest/pos/products
  categoryPath: /servlet/rest/pos/categories
  workspacePath: /servlet/rest/pos/workspaces
  posPath: /servlet/rest/pos/poss
  userPath: /servlet/rest/pos/users
  receiptPath: /servlet/rest/pos/receipts
  invoicePath: /servlet/rest/pos/invoices
  ticketPath: /servlet/rest/pos/tickets
  checkoutPath: /servlet/checkout
  sequencePath: /servlet/rest/pos/sequences
  contactPath: /servlet/rest/pos/contacts
  warehousePath: /servlet/rest/pos/warehouses
  inventoryPath: /servlet/rest/pos/inventory
  printerPath: /servlet/rest/pos/printers
  configPath: /servlet/rest/pos/config
  balancePath: /servlet/rest/pos/balance

auth:
  user: Administrator
  password: Administrator

jwt:
  secret: ThisIsNotVerySecret
  expiration: 1000


---

spring:
  profiles: demo
  autoconfigure:
    exclude:
  data:
    mongodb:
      database: efapsDemoPOS

name: POS-Demo-Backend
