name: POS-Backend

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration
  data:
    mongodb:
      database: efapsPOS

server:
#  address: 192.168.1.100
#  port: 8888
  http2:
    enabled: true

org:
  quartz:
    threadPool:
      threadCount: 2
    jobs:
      syncPayables: # syncs Receipts, Invoices and Tickets with related Balances
        interval: 120  #Interval in seconds
      syncContacts:
        interval: 300

efaps:
  baseUrl: http://localhost:8888/eFaps
  backendPath: /servlet/rest/pos/backend
  productPath: /servlet/rest/pos/{identifier}/products
  categoryPath: /servlet/rest/pos/{identifier}/categories
  workspacePath: /servlet/rest/pos/{identifier}/workspaces
  posPath: /servlet/rest/pos/{identifier}/poss
  userPath: /servlet/rest/pos/{identifier}/users
  receiptPath: /servlet/rest/pos/{identifier}/receipts
  invoicePath: /servlet/rest/pos/{identifier}/invoices
  ticketPath: /servlet/rest/pos/{identifier}/tickets
  checkoutPath: /servlet/checkout
  sequencePath: /servlet/rest/pos/{identifier}/sequences
  contactPath: /servlet/rest/pos/{identifier}/contacts
  warehousePath: /servlet/rest/pos/{identifier}/warehouses
  inventoryPath: /servlet/rest/pos/{identifier}/inventory
  printerPath: /servlet/rest/pos/{identifier}/printers
  configPath: /servlet/rest/pos/{identifier}/config
  balancePath: /servlet/rest/pos/{identifier}/balance

auth:
  user: Administrator
  password: Administrator

jwt:
  secret: ThisIsNotVerySecret
  expiration: 1000


---

spring:
  profiles: demo
  autoconfigure:
    exclude:
  data:
    mongodb:
      database: efapsDemoPOS

name: POS-Demo-Backend
