
name: POS-Backend

spring:
    data:
      mongodb:
        database: efapsPOS

server:
  servlet:
    contextPath: /pos


efaps:
  restUrl: http://localhost:8888/eFaps/servlet/rest
  productPath: /pos/products

auth:
  user: Administrator
  password: Administrator
