
name: POS-Backend

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration
  data:
    mongodb:
      database: efapsPOS

org:
  quartz:
    threadPool:
      threadCount: 2
    jobs:
      syncReceipts:
        interval: 30  #Interval in seconds

server:
  servlet:
    contextPath: /pos/api


efaps:
  baseUrl: http://localhost:8888/eFaps
  productPath: /servlet/rest/pos/products
  categoryPath: /servlet/rest/pos/categories
  workspacePath: /servlet/rest/pos/workspaces
  posPath: /servlet/rest/pos/poss
  userPath: /servlet/rest/pos/users
  receiptPath: /servlet/rest/pos/receipts
  checkoutPath: /servlet/checkout
  sequencePath: /servlet/rest/pos/sequences
  contactPath: /servlet/rest/pos/contacts

auth:
  user: Administrator
  password: Administrator

jwt:
  secret: ThisIsNotVerySecret
  expiration: 1000


---

spring:
  profiles: demo
  autoconfigure:
    exclude:
  data:
    mongodb:
      database: efapsDemoPOS

name: POS-Demo-Backend
