name: POS-Backend
version: 0.0.0

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration

mongoClientURI: mongodb://localhost:27017/efapsPOS

server:
#  address: 192.168.1.100
#  port: 8888
  http2:
    enabled: true

org:
  quartz:
    threadPool:
      threadCount: 2
    jobs:
      syncPayables: # syncs Receipts, Invoices and Tickets with related Balances
        interval: 120  #Interval in seconds
      syncContacts:
        interval: 300
      syncInventory:
        interval: 300

efaps:
  baseUrl: http://localhost:8888/eFaps
  backendPath: /servlet/rest/pos/backend
  productPath: /servlet/rest/pos/{identifier}/products
  categoryPath: /servlet/rest/pos/{identifier}/categories
  workspacePath: /servlet/rest/pos/{identifier}/workspaces
  posPath: /servlet/rest/pos/{identifier}/poss
  userPath: /servlet/rest/pos/{identifier}/users
  orderPath: /servlet/rest/pos/{identifier}/orders
  receiptPath: /servlet/rest/pos/{identifier}/receipts
  invoicePath: /servlet/rest/pos/{identifier}/invoices
  ticketPath: /servlet/rest/pos/{identifier}/tickets
  checkoutPath: /servlet/checkout
  sequencePath: /servlet/rest/pos/{identifier}/sequences
  contactPath: /servlet/rest/pos/{identifier}/contacts
  warehousePath: /servlet/rest/pos/{identifier}/warehouses
  inventoryPath: /servlet/rest/pos/{identifier}/inventory
  printerPath: /servlet/rest/pos/{identifier}/printers
  configPath: /servlet/rest/pos/{identifier}/config
  balancePath: /servlet/rest/pos/{identifier}/balance

auth:
  user: Administrator
  password: Administrator

staticWeb:
  ignore:
    - "/"
    - "/kiosk/**"
    - "/pos/**"
    - "/**/*.html"
    - "/favicon.ico"
    - "/**/favicon.png"
    - "/**/*.html"
    - "/**/*.css"
    - "/**/*.js"
    - "/**/*.json"
    - "/**/*.svg"
  views:
    "[/kiosk]": "forward:/kiosk/index.html"
    "[/kiosk/config]": "forward:/kiosk/index.html"
    "[/kiosk/categories]": "forward:/kiosk/index.html"
    "[/kiosk/categories/*]": "forward:/kiosk/index.html"
    "[/kiosk/login]": "forward:/kiosk/index.html"
    "[/kiosk/end]": "forward:/kiosk/index.html"
    "[/pos]": "forward:/pos/index.html"
    "[/pos/login]": "forward:/pos/index.html"
  resources:
    "[/kiosk/**]": "file:/home/jan-moxter/Development/git/nodejs/synerkiosk-cashcontrol/dist/synerkiosk-cashcontrol/"
    "[/pos/**]": "file:/home/jan-moxter/Development/git/nodejs/eFaps-POS-FE/dist/"

jwt:
  secret: ThisIsNotVerySecret
  expiration: 300  #accessToken expiration in seconds
  deviation: 60 #devation for the refresh token in seconds => expires in expiration

---

spring:
  profiles: demo
  autoconfigure:
    exclude:
  data:
    mongodb:
      database: efapsDemoPOS

name: POS-Demo-Backend
