name: POS-Backend
version: 0.0.0
syncOnStartup: true
maxSearchResult: 100
timeZone: America/Lima


spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.embedded.EmbeddedMongoAutoConfiguration
  quartz:
    scheduler-name: Quartz-Scheduler
    properties:
      org.quartz.threadPool.threadCount: 1
      org.quartz.scheduler.skipUpdateCheck: true

mongoClientURI: mongodb://localhost:27017/efapsPOS

server:
#  address: 192.168.1.100
#  port: 8888
  http2:
    enabled: true

org:
  quartz:
    jobs:
      syncPayables: # syncs Receipts, Invoices and Tickets with related Balances
        interval: 120  #Interval in seconds
      syncContacts:
        interval: 300
      syncInventory:
        interval: 300

efaps:
  baseUrl: http://localhost:8888/eFaps
  backendPath: /servlet/rest/pos/backend
  productPath: /servlet/rest/pos/{identifier}/products
  productLimit: 500
  categoryPath: /servlet/rest/pos/{identifier}/categories
  workspacePath: /servlet/rest/pos/{identifier}/workspaces
  posPath: /servlet/rest/pos/{identifier}/poss
  userPath: /servlet/rest/pos/{identifier}/users
  orderPath: /servlet/rest/pos/{identifier}/orders
  receiptPath: /servlet/rest/pos/{identifier}/receipts
  invoicePath: /servlet/rest/pos/{identifier}/invoices
  ticketPath: /servlet/rest/pos/{identifier}/tickets
  creditnotePath: /servlet/rest/pos/{identifier}/creditnotes
  checkoutPath: /servlet/checkout
  sequencePath: /servlet/rest/pos/{identifier}/sequences
  contactPath: /servlet/rest/pos/{identifier}/contacts
  warehousePath: /servlet/rest/pos/{identifier}/warehouses
  inventoryPath: /servlet/rest/pos/{identifier}/inventory
  printerPath: /servlet/rest/pos/{identifier}/printers
  configPath: /servlet/rest/pos/{identifier}/config
  balancePath: /servlet/rest/pos/{identifier}/balance
  exchangeRatePath: /servlet/rest/pos/{identifier}/exchange-rates
  employeePath: /servlet/rest/pos/{identifier}/employees

auth:
  user: Administrator
  password: Administrator

taxpayerRegistry:
  baseUrl: https://consulta-ruc.synercom.pe
  queryPath: query

jwt:
  secret: ThisIsNotVerySecretButItIsAtLeastLongEnoughToHaveMoreThan256Bits
  expiration: 300  #accessToken expiration in seconds
  deviation: 60 #devation for the refresh token in seconds => expires in expiration

---

spring:
  config:
    activate:
      on-profile: demo

  data:
    mongodb:
      database: efapsDemoPOS

demo:
  users: "classpath:users.json"
  products: "classpath:products.json"
  workspaces: "classpath:workspaces.json"
  poss: "classpath:poss.json"
  categories: "classpath:categories.json"
  sequences: "classpath:sequences.json"
  contacts: "classpath:contacts.json"
  files: "classpath:images.json"

name: POS-Demo-Backend


---

spring:
  config:
    activate:
      on-profile: embedded
  autoconfigure:
    exclude:
